/**
 * Loremaker Universe Characters
 * To add new characters, simply add objects to the array below
 */

export const LOREMAKER_CHARACTERS = [
  {
    id: 'loremaker-1',
    character: 'Aether the Wise',
    alias: 'The Timekeeper',
    gender: 'Male',
    alignment: 'Neutral Good',
    location: 'The Eternal Library',
    powers: 'Time manipulation, Cosmic knowledge',
    faction: 'The Watchers',
    era: 'Ancient Era',
    status: 'Active',
    description: 'Guardian of temporal balance and keeper of all knowledge',
    longDescription: 'Aether has watched over the timeline for millennia, ensuring that the fabric of reality remains intact. His vast knowledge spans across all dimensions.',
    stories: 'The Timekeeper Chronicles',
    url: 'https://via.placeholder.com/600x900/6B46C1/ffffff?text=Aether+the+Wise',
    coverUrl: 'https://via.placeholder.com/600x900/6B46C1/ffffff?text=Aether+the+Wise',
    thumbnailUrl: 'https://via.placeholder.com/600x900/6B46C1/ffffff?text=Aether+the+Wise',
    galleryImages: [
      'https://via.placeholder.com/600x900/6B46C1/ffffff?text=Aether+1',
      'https://via.placeholder.com/600x900/6B46C1/ffffff?text=Aether+2',
    ],
    type: 'character',
  },
  {
    id: 'loremaker-2',
    character: 'Nova Starlight',
    alias: 'The Celestial Flame',
    gender: 'Female',
    alignment: 'Chaotic Good',
    location: 'The Nebula Citadel',
    powers: 'Stellar energy, Flight, Cosmic fire',
    faction: 'Star Guardians',
    era: 'Modern Era',
    status: 'Active',
    description: 'A cosmic warrior who harnesses the power of dying stars',
    longDescription: 'Born from a supernova, Nova protects the galaxy from dark forces seeking to extinguish the light of the universe.',
    stories: 'Guardians of the Cosmos',
    url: 'https://via.placeholder.com/600x900/EC4899/ffffff?text=Nova+Starlight',
    coverUrl: 'https://via.placeholder.com/600x900/EC4899/ffffff?text=Nova+Starlight',
    thumbnailUrl: 'https://via.placeholder.com/600x900/EC4899/ffffff?text=Nova+Starlight',
    galleryImages: [
      'https://via.placeholder.com/600x900/EC4899/ffffff?text=Nova+1',
      'https://via.placeholder.com/600x900/EC4899/ffffff?text=Nova+2',
    ],
    type: 'character',
  },
  {
    id: 'loremaker-3',
    character: 'Shadow Wraith',
    alias: 'The Phantom King',
    gender: 'Male',
    alignment: 'Neutral Evil',
    location: 'The Void Realm',
    powers: 'Shadow manipulation, Teleportation, Fear inducement',
    faction: 'The Dark Council',
    era: 'Dark Age',
    status: 'Active',
    description: 'Master of shadows who rules over the realm between light and darkness',
    longDescription: 'Once a noble knight, Shadow Wraith was corrupted by forbidden magic and now commands an army of shadow beings.',
    stories: 'Tales from the Void',
    url: 'https://via.placeholder.com/600x900/7C3AED/ffffff?text=Shadow+Wraith',
    coverUrl: 'https://via.placeholder.com/600x900/7C3AED/ffffff?text=Shadow+Wraith',
    thumbnailUrl: 'https://via.placeholder.com/600x900/7C3AED/ffffff?text=Shadow+Wraith',
    galleryImages: [
      'https://via.placeholder.com/600x900/7C3AED/ffffff?text=Shadow+1',
    ],
    type: 'character',
  },
  {
    id: 'loremaker-4',
    character: 'Luna Silverleaf',
    alias: 'The Moon Archer',
    gender: 'Female',
    alignment: 'Lawful Good',
    location: 'Silverwood Forest',
    powers: 'Lunar magic, Archery mastery, Nature communication',
    faction: 'Forest Guardians',
    era: 'Medieval Era',
    status: 'Active',
    description: 'An elven archer blessed by the moon goddess',
    longDescription: 'Luna protects the ancient forests using arrows imbued with moonlight, capable of piercing through any darkness.',
    stories: 'Legends of Silverwood',
    url: 'https://via.placeholder.com/600x900/10B981/ffffff?text=Luna+Silverleaf',
    coverUrl: 'https://via.placeholder.com/600x900/10B981/ffffff?text=Luna+Silverleaf',
    thumbnailUrl: 'https://via.placeholder.com/600x900/10B981/ffffff?text=Luna+Silverleaf',
    galleryImages: [
      'https://via.placeholder.com/600x900/10B981/ffffff?text=Luna+1',
      'https://via.placeholder.com/600x900/10B981/ffffff?text=Luna+2',
      'https://via.placeholder.com/600x900/10B981/ffffff?text=Luna+3',
    ],
    type: 'character',
  },
  {
    id: 'loremaker-5',
    character: 'Blaze Inferno',
    alias: 'The Fire Lord',
    gender: 'Male',
    alignment: 'Chaotic Neutral',
    location: 'Volcanic Throne',
    powers: 'Pyrokinesis, Lava manipulation, Heat immunity',
    faction: 'Elemental Lords',
    era: 'Primordial Era',
    status: 'Active',
    description: 'Ruler of all flames and volcanic forces',
    longDescription: 'Blaze commands the primal power of fire itself, able to summon volcanic eruptions and rivers of molten lava at will.',
    stories: 'Reign of Fire',
    url: 'https://via.placeholder.com/600x900/F59E0B/ffffff?text=Blaze+Inferno',
    coverUrl: 'https://via.placeholder.com/600x900/F59E0B/ffffff?text=Blaze+Inferno',
    thumbnailUrl: 'https://via.placeholder.com/600x900/F59E0B/ffffff?text=Blaze+Inferno',
    galleryImages: [],
    type: 'character',
  },
];

// Helper to get loremaker data in the expected format
export function getLoremakerData() {
  return {
    items: LOREMAKER_CHARACTERS,
  };
}
